source 'https://github.com/CocoaPods/Specs.git'

target "PlayeAndMap" do
	
	platform :ios, '8.0'
	use_frameworks!
	inhibit_all_warnings!

	pod 'SDWebImage', '~> 4.2.2'
	pod 'Masonry', '~> 1.1.0'
	pod 'MBProgressHUD', '~> 1.1.0'
	pod 'BlocksKit', '~> 2.2.5'
	pod 'pop', '~> 1.0.10'
	pod 'ReactiveObjC', '~> 3.0.0'
	pod 'TZImagePickerController', '~> 1.9.8'
	pod 'WRNavigationBar', '~> 1.1.0'
	#pod 'ZFPlayer', '~> 2.1.5'

	pod 'AMap3DMap-NO-IDFA', '~> 5.6.0'

end
