source 'https://github.com/CocoaPods/Specs.git'

target "BlockDemo" do
	
	platform :ios, '8.0'
	use_frameworks!
	inhibit_all_warnings!

	pod 'Masonry', '~> 1.0.0'
	pod 'ReactiveCocoa', '2.5'
	pod 'BlocksKit', '~> 2.2.5'
end
