source 'https://github.com/CocoaPods/Specs.git'

target "Text" do
	
	platform :ios, '8.0'
	use_frameworks!
	inhibit_all_warnings!
	
	pod 'AFNetworking', '~> 3.1.0'
	pod 'SDWebImage', '~> 3.7.5'
	pod 'MJRefresh', '~> 3.1.0'
	#pod 'JSPatchPlatform'
	pod 'Masonry', '~> 1.0.0'
	pod 'MBProgressHUD', '~> 0.9.2'
	#pod 'FMDB', '~> 2.6.2'
	pod 'ProtocolBuffers', '~> 1.9.10'
	pod 'ReactiveCocoa', '2.5'
	#pod 'LinqToObjectiveC', '~> 2.0.0'
	pod 'BlocksKit', '~> 2.2.5'
	#键盘
	pod 'IQKeyboardManager', '~> 4.0.2'
	#pod 'RDVTabBarController', '~> 1.1.9'
	pod 'TZImagePickerController', '~> 1.7.1'
	pod 'MWPhotoBrowser', '~> 2.1.2'
	pod 'Toast', '~> 3.0'
	#轮滑
	pod 'SDCycleScrollView', '~> 1.64'
	#抽屉
	#pod 'MMDrawerController', '~> 0.6.0'
	
	pod 'UMengUShare', '~> 6.4.5'
	
	pod 'UMengAnalytics'
	
	pod 'Bugtags', '~> 1.3.1',:configurations => ['Debug']
	
	pod 'Reveal-SDK', :configurations => ['Debug']
	
	pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'
	
end
